# Generated by Django 5.2 on 2025-04-26 22:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('OST', 'Original Soundtrack'), ('GR', 'Gamerip')], default='OST', max_length=5)),
                ('game', models.CharField(choices=[('SE', 'Soul Edge'), ('SB', 'Soul Blade'), ('SC', 'Soulcalibur'), ('SCII', 'Soulcalibur II'), ('SCIII', 'Soulcalibur III'), ('SCL', 'Soulcalibur Legends'), ('SCIV', 'Soulcalibur IV'), ('SCBD', 'Soulcalibur: Broken Destiny'), ('SCV', 'Soulcalibur V'), ('SCVI', 'Soulcalibur VI')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.DurationField()),
                ('description', models.CharField(max_length=255)),
                ('variation_type', models.CharField(choices=[('ORI', 'Original'), ('ARR', 'Arranged'), ('EXT', 'Extended'), ('SHORT', 'Shortened'), ('FRAG', 'Fragment')], default='ORI', max_length=6)),
                ('original_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='music_sc.song')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_number', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_sc.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_sc.song')),
            ],
            options={
                'ordering': ['album', 'song_number'],
                'unique_together': {('album', 'song')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', through='music_sc.AlbumSong', to='music_sc.song'),
        ),
    ]
