# Generated by Django 5.2 on 2025-04-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
