# Generated by Django 5.2 on 2025-04-28 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sc', '0002_alter_song_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='code',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
