# Generated by Django 5.2 on 2025-04-28 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sc', '0003_alter_album_code_alter_song_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
